### ISSUE TITLE
Wallet Alpha 🪐 - Pilot Avant Garden

### ISSUE THREAD

**Issue by micolsalomone** [ForkbombEu/wallet#115]
Objective: Test Mobile Solutions for Wallet and Verifier

Deadline: February 16th

Duration: 3 Weeks

Roles: UI, Front-end, Infrastructure

Things to Consider:

- Some microservices are missing (Rebecca)
- Requires multilingual support

## Tasks:

Wallet:

 - [x] ForkbombEu/didroom-components#43
 - [x] #117
- [x] #118
- [x] #119
- [x] Integrate Lottie animation for credential issuance process - Design pending
- [x] #120
- [x] #122
- [x] #121
- [ ] Implement permission requests for biometrics, camera, and notifications (New page) design is pending
